# This file is managed by https://github.com/nexient-llc/.github/

# DO NOT make changes to this file directly from within any other
# repo then mentioned above as they will be overwritten upon the
# next sync.

# NOTE: we are temporarily throwing the kitchen sink of variables
# at the workflow until we come up with a better solution at a
# future date.
env:
  TF_VAR_github_org: ${{ secrets.TF_VAR_GITHUB_ORG }}
  TF_VAR_github_token:  ${{ secrets.TF_VAR_GITHUB_TOKEN }}

name: pipeline-check
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # pull entire history to ensure pre-merge functions properly
      - uses: nexient-llc/.github/actions/configure@main
      - uses: nexient-llc/.github/actions/check@main
      - uses: nexient-llc/.github/actions/pre-merge@main
